version: 2

updates:
  # NPM dependencies: keep non-breaking updates together
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly

    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      major-updates:
        update-types:
          - major
        patterns:
          - '*'

    open-pull-requests-limit: 1

  # GitHub Actions: keep non-breaking updates together
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      major-updates:
        update-types:
          - major
        patterns:
          - '*'

    open-pull-requests-limit: 1
