version: 2

updates:
  # NPM dependencies: keep non-breaking updates together
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly

    groups:
      major-and-minor-updates:
        update-types:
          - major
          - minor
        patterns:
          - '*'

    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch

    open-pull-requests-limit: 1

  # GitHub Actions: keep non-breaking updates together
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

    groups:
      major-and-minor-updates:
        update-types:
          - major
          - minor
        patterns:
          - '*'

    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch

    open-pull-requests-limit: 1
