name: Validate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    if: github.repository_owner == 'FredrikM97'
    name: 'HACS Validation'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: 'Run HACS validation'
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a
        with:
          category: 'plugin'
